### ISSUE TITLE
How to tell EasyOTA that there is a wifi connection already?

### ISSUE THREAD

**Issue by markg85** [jeroenvermeulen/JeVe_EasyOTA#10]
Hi,

I'm trying to use this library along with the WiFiManager [1]. That library obviously manages the wifi and is run _before_ EasyOTA.

EasyOTA seems to be tailored towards always making a wifi connection. While that is great if a wifi manager isn't used. It's a bit of a pain if it is.

So i'm hoping for an option to tell EasyOTA to just use whatever wifi connection is available. Kinda like the PubSubClient [2] library where you don't have to tell it anything [3] and yet it works when it has a wifi connection.

[1] https://github.com/tzapu/WiFiManager
[2] https://github.com/knolleary/pubsubclient
[3] oke, i have to give it a "WiFiClient" instance, but that literally is just making the instance and be done with it. No configuration whatsoever.

**Edit**
Turns out what i want is literally as simple as this in your **setup** and **after** you have a Wifi connection:
```
  // ...
  // ... your wifi connection code.
  // ...
  ArduinoOTA.setPort(8266); // optional
  ArduinoOTA.setHostname("Your_device_hostname");
  ArduinoOTA.begin();
```

and in your **loop** function, just at this at the very top:
```
  ArduinoOTA.handle();
```

That really is all there is to it and makes it work.
Sure, it misses some additional EasyOTA features.... but for me, this was all i needed.

**Comment by jeroenvermeulen** [comment]
Hi @markg85, do I understand correct you made it work without EasyOTA?
If that's OK for you, I don't think we need to change anything.

**Comment by markg85** [comment]
> Hi @markg85, do I understand correct you made it work without EasyOTA?
> If that's OK for you, I don't think we need to change anything.

Yes.

I did get it working with WiFiManager even though it wasn't as neat as EasyOTA. I had to hack that a little to make it more user friendly (like even giving it a hostname and adding in mDNS).

Closing this one.
