### ISSUE TITLE
Why GPL?

### ISSUE THREAD

**Issue by tamusjroyce** [jeroenvermeulen/JeVe_EasyOTA#14]
Just curious, why the change to GPL? Are you selling licenses now? I don't see many changes from Felix's version.  https://gitlab.com/regenbogencode/easyota?utm_source=platformio&utm_medium=piohome

Did you obtain permission from Felix before licensing? It doesn't look like his repository has a license associated.

**Comment by jeroenvermeulen** [comment]
The 2 libraries are not connected. 
They only happen to have partly the same name.

Met vriendelijke groet,
Jeroen Vermeulen • MageHost.pro
