### ISSUE TITLE
Kindly checkout a little bit refactored version

### ISSUE THREAD

**Issue by foxis** [jeroenvermeulen/JeVe_EasyOTA#3]
Hi, 
I wanted a little bit more from your nice little ArduinoOTA wrapper, so I rolled my own here https://github.com/foxis/EasyOTA

Since my work is based on your code and I have added GPL license to it, I would like you to give me your thoughts on this.
Should I continue development of the library in my own fork separately, or should I issue a pull request ?

In the future I am planning to create a series of Easy* libraries, e.g. EasyUI which would be similar to ESPUI library, etc.

**Comment by jeroenvermeulen** [comment]
Hi @foxis, a PR would be more than welcome!
This PR will make it very easy for me to see your improvements.
If on the longer term you would do a lot more work in the library than I do, I will probably give you access to merge PRs yourself, of hand over the entire library to you.
Is this OK?

**Comment by foxis** [comment]
Created a PR
Have a look :}

my plans for the library:
* HTTP update
* Web server update
* MQTT update
* code sync between adhoc network of ESP devices (don't have projects that require this, but it would be quite a great thing to have)

**Comment by foxis** [comment]
Initially I was planning to branch it and brand as a different library, thus the changes to library.json, etc.

**Comment by jeroenvermeulen** [comment]
Could you submit a PR with as little changes as possible?
Renaming the library from `Jeve_EasyOTA` to `EasyOTA` is OK to me, but it would be better to submit your changes first, and do the rename in a separate PR. 
This makes it a lot easier to keep track of the changes.

**Comment by foxis** [comment]
I'll make a new PR friendly branch taking into account all the comments then. And create a new PR with it.

**Comment by jeroenvermeulen** [comment]
Merged, thanks @foxis
