### ISSUE TITLE
PlatformIO can't find header file due to broken library.json

### ISSUE THREAD

**Issue by gordoste** [jeroenvermeulen/JeVe_EasyOTA#6]
Thanks for the nice library! I've been trying to use it in platformIO, but it doesn't work properly. PlatformIO Library Dependency Finder can't find the header file, and if you enable verbose mode, you'll see why:

Skip library with broken manifest: C:\Users\stephen\Documents\PlatformIO\Projects\moonboard\.piolibdeps\EasyOTA_ID1975

The library.json has an extra comma on line 13. I can do a PR if you really want me to :)

**Comment by jeroenvermeulen** [comment]
Thanks for reporting, fixed in commit d7dbb76510d30cb2bae4aaef34293bc3d85702d2
